"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import React,{useState,createContext} from 'react'
const inter = Inter({ subsets: ['latin'] })
import NavBar from "./comp/NavBar.jsx"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const Mycontext = createContext([])

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [value, setValue] = useState<data>([])
console.log("from layout", value);

  return (
    <Mycontext.Provider value={{value,setValue}}>
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        {children}</body>
    </html>
    </Mycontext.Provider>
  )
}
export {Mycontext}
