"use client"
import './globals.css'
import { Inter } from 'next/font/google'

import React,{useState,createContext} from 'react'

const inter = Inter({ subsets: ['latin'] })
import NavBar from "./comp/NavBar.jsx"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const MyContext = createContext([]);


export default function RootLayout({ children,}: {children: React.ReactNode}) {
  const [contextValue, setContextValue] = useState<typeof users>([]);
console.log("global context",contextValue);

  const updateContext = (data :typeof users) => {
    setContextValue(data);
  };
  return (
    <MyContext.Provider value={{contextValue ,updateContext}}>

    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        {children}</body>
    </html>

    </MyContext.Provider>
  )
}
export {MyContext}

